### ISSUE TITLE
the documentation is confusing.

### ISSUE THREAD

**Issue by bryantvdberg** [wanze/TemplateEngineFactory#14]
I used your documention of TemplateEngineFactory to install TemplateEngineFactory and twig template. But the classnames are not up-to-date. And there is no good explaination of installing it the right way. after 2 hours figuring out how to do it and delete the files ever time. The composer command at TemplateEngineFactory worked.

**Comment by wanze** [comment]
Hi @bryantvdberg 

Sorry to hear you've had problems with the installation. What do you mean by "the classnames are not up-to-date"?

To install TemplateEngineTwig + TemplateEngineFactory in one step, execute the following command in your ProcessWire root directory:

```
composer require wanze/template-engine-twig:^2.0
```

This should install both modules, which you'll need to activate and configure in ProcessWire afterwards. Can you point to the part in the docs you're finding confusing, in order to improve it?

Cheers
